Implement advanced authorization checks using roles and policies
filamentphp/filament pull request #106
Opened 2021-03-07 00:50 UTC by danharrin

Current considerations:
- How does each individual row in the table know if it is editable or not?
- If more than one record is selected for delete but only one is deletable according to the policy, what should happen?

2021-03-07 18:35 UTC, kfvit-andreaskviby commented
Hey, just a thought from Mr Kviby here :) I would like to add if the record is viewable at all for the currently logged in user.

2021-03-07 18:39 UTC, ryangjchandler commented
> Hey, just a thought from Mr Kviby here :) I would like to add if the record is viewable at all for the currently logged in user.

You would be able to do this using a model policy or using one of Filament's roles.

2021-03-10 09:26 UTC, ryangjchandler approved these changes

2021-03-10 09:48 UTC, ryangjchandler requested changes

2021-03-10 09:48 UTC, ryangjchandler commented on resources/views/relation-manager.blade.php
> +                @if ($this->canCreate())
```suggestion
                @if ($this->canDelete())
```

2021-03-10 09:52 UTC, merged