Support non-streamed downloads
filamentphp/filament pull request #14591
Opened 2024-10-21 14:37 UTC by Robertbaelde

## Description

Some hosting environments do not support streamed downloads (mainly environments running on lambda like Laravel Vapor or Bref). This makes the export functionality not work because the downloaders assume we can do a streamed download. 

This PR adds a config to enable/disable streamed downloads. When disabled, the downloader will write the contents to one file and uploads it to the disk (so we don't have to re-do the generation on multiple downloads).  

## Visual changes

N/A

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

2024-10-22 09:07 UTC, danharrin requested changes
Please can you remove the part that saves new files to the disk? I am conscious we are already writing a lot of this data to the disk and XLSX files are already generated ahead of time, so we can probably avoid that for now while still allowing non-streamed downloads.

Please be aware that you may hit the memory limit more often if you don't stream

I would also double check that Vapor definitely doesnt support streamed downloads, because that doesn't really sound right to me 🤔

2024-10-23 01:08 UTC, austincarpenter commented
To get things working on Vapor, you need to add the `X-Vapor-Base64-Encode` header in the response. (See https://docs.vapor.build/projects/development.html#binary-responses)

I only use the XLSX downloader so I've simply subclassed `XlsxDownloader`, replacing the `__invoke()` function to add the header:

```php
public function __invoke(Export $export): StreamedResponse
{
    return tap(parent::__invoke($export), function (StreamedResponse $response) {
        $response->headers->set('X-Vapor-Base64-Encode', true);
    });
}
```

```php
$this->app->bind(BaseXlsxDownloader::class, XlsxDownloader::class);
```

2024-10-23 06:20 UTC, danharrin commented
Is there a way we can detect Vapor within Filament and do this on the users behalf? Instead of disabling streaming?

2024-10-23 09:08 UTC, Robertbaelde commented
> Is there a way we can detect Vapor within Filament and do this on the users behalf? Instead of disabling streaming?

For Vapor: `isset($_ENV['VAPOR_SSM_PATH']) || isset($_SERVER['VAPOR_SSM_PATH'])`
For Bref: `env('LAMBDA_TASK_ROOT')` (detects Lambda runtime) or `env('BREF_LOOP_MAX')`

Will try to reshape this PR a bit with the given feedback. I'm afraid for Bref downloads larger than 6MB should come from a disk (s3), see: https://bref.sh/docs/use-cases/http/binary-requests-responses 

Not sure if/how Vapor mitigates that though

2024-11-29 09:05 UTC, danharrin commented
Hi, please reopen this if you decide to implement the requested changes. Thank you!

2024-11-29 09:05 UTC, closed without merging

2026-07-27 04:25 UTC, bretto36 commented
@danharrin I still get 502 Bad Gateway errors when using laravel vapor and filament on large downloads. Even some that are < 1MB 

https://docs.vapor.build/projects/development#binary-responses

Lambda limits responses to 6MB. If you need to serve a larger file, consider returning a signed, temporary S3 URL that your user may use to download the file directly from S3.

----

Even if there was a way to apply custom Downloaders i could create a 3rd party package that people could simply use the formats() method on the Exporter class to push to their own