extract create modal actions
filamentphp/filament pull request #1516
Opened 2022-02-09 10:09 UTC by wychoong

2022-02-09 10:12 UTC, ryangjchandler requested changes

2022-02-09 10:12 UTC, ryangjchandler commented on packages/admin/src/Resources/Pages/ListRecords/Concerns/CanCreateRecords.php
> +use Filament\Pages\Actions\Modal\Actions\ButtonAction as ModalButtonActions;
Can we use a relative namespace instead of an aliased import please.

2022-02-11 19:52 UTC, danharrin commented
Method names like `getCancelModalAction()` aren't appropriate for traits like this, as there are many cancel actions on the class. Prefix each method name with `getCreateAction`, so `getCreateActionCancelModalAction()` or similar. Also, do you need to do the same for `CanAttachRecords`?

2022-02-12 04:47 UTC, wychoong commented
> Method names like `getCancelModalAction()` aren't appropriate for traits like this, as there are many cancel actions on the class. Prefix each method name with `getCreateAction`, so `getCreateActionCancelModalAction()` or similar. Also, do you need to do the same for `CanAttachRecords`?

Will look into both.

Actually the purpose of extracting is I want to remove createAndCreateAnother. Do you think it would be better to:
- a config to disable createAndCreateAnother globally 
- Add prepend/append form actions method (if not available yet)

2022-02-21 08:53 UTC, wychoong commented
> Prefix each method name with `getCreateAction`,

this will result to 
```php
$this->getCreateActionCreateModalAction(),
$this->getCreateActionCreateAndCreateAnotherModalAction(),
$this->getCreateActionCancelModalAction(),
```
is that ok?

2022-02-21 11:17 UTC, danharrin commented
> > Prefix each method name with `getCreateAction`,
> 
> this will result to
> 
> ```
> $this->getCreateActionCreateModalAction(),
> $this->getCreateActionCreateAndCreateAnotherModalAction(),
> $this->getCreateActionCancelModalAction(),
> ```
> 
> is that ok?

Yup that's fine

2022-02-21 11:23 UTC, wychoong commented
> > > Prefix each method name with `getCreateAction`,
> > 
> > 
> > this will result to
> > ```
> > $this->getCreateActionCreateModalAction(),
> > $this->getCreateActionCreateAndCreateAnotherModalAction(),
> > $this->getCreateActionCancelModalAction(),
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > is that ok?
> 
> Yup that's fine

the PR is ready, it's now is more than just extracting modal actions 😅  but it's to make resource actions consistent with RM.

one part I'm not sure is it the best to set the static property globally with FilamentManager and RelationManager

2022-03-01 23:45 UTC, merged