Support custom admin panel paths with other parameters
filamentphp/filament pull request #1517
Opened 2022-02-09 10:11 UTC by ralphjsmit

I wanted to use Filament admin with a URL like: `example.com/organizations/7165e010-0f3d-4f2f-86ae-253b6bb3778b`.

In the config file we can set the url:
```php
'path' => 'organizations/{organization}',
```

I have a middleware applied on every single route via the `$middleware` in the kernel:
```php
// ...

URL::defaults([
    'organization' => $organizationUuid,
]);
```

I confirmed with a `dd()` that this code is being run, so that should be good. Having this works for 80%, the only problem was that the JavaScript was not being loaded:

```
(404) https://example.test/organizations/7165e010-0f3d-4f2f-86ae-253b6bb3778b/core/assets/app.js?id=937c2814f9d988613ece
```

I took a look at the AssetController and I found out that the way Filament uses route model binding is the error here:
```php
    public function __invoke(string $file, string $b)
    {
        ray($file); // This is the organization Eloquent model cast to json
        ray($b); // This turns out to be the correct filename.
         
        // This is correct
        $file = request()->file;
```

To fix that, I updated the AssetController like:

```php
    public function __invoke(string $file)
    {
        // The first argument to __invoke will be the first parameter in the complete route,
        // and not the parameter named 'file'. This means that the original $file parameter will
        // not be the correct parameter in cases where people use the admin panel with a custom
        // path like "/admin/{userUUID}/".
        $file = request()->file ?? $file;
```

I tried creating a test, but I'm not aware of a way to flush the registered routes and run the registration process again:

```php
it('can support admin panel paths with other parameters', function () {
    config()->set('filament.path', 'admin');

    $this->get(route('filament.asset', [
        'id' => Filament\get_asset_id('app.js'),
        'file' => 'app.js',
    ]))->assertOk();

    config()->set('filament.path', 'admin/{param}');

    // Flush registered routes and register them again

    $this->get(route('filament.asset', [
        'id' => Filament\get_asset_id('app.js'),
        'file' => 'app.js',
    ]))->assertOk();
});
```

2022-02-09 10:14 UTC, ryangjchandler commented
@ralphjsmit Thanks for this. @danharrin What do you think about registering the assets route on a pseudo-private URL like `/_filament` instead?

2022-02-09 22:02 UTC, danharrin commented
Yeah I agree with Ryan here - we should just move the assets away from the main admin path.

2022-02-09 22:03 UTC, danharrin commented
Even just `/filament` will work - without the underscore.

2022-02-10 12:39 UTC, ralphjsmit commented
Good idea! Can I help with this or should this be just as simple as updating the routes file?

2022-02-10 12:48 UTC, danharrin commented
You can update the routes file if you want

2022-02-10 13:20 UTC, ralphjsmit commented
Done! Tested it and works smooth.

2022-02-10 16:14 UTC, ryangjchandler requested changes

2022-02-10 16:14 UTC, ryangjchandler commented on packages/admin/src/Http/Controllers/AssetController.php
> +        $file = request()->file ?? $file;
Do we still need this?

2022-02-11 13:52 UTC, ralphjsmit commented on packages/admin/src/Http/Controllers/AssetController.php
> +        $file = request()->file ?? $file;
Not necessarily, I removed it.

2022-02-11 14:15 UTC, ryangjchandler requested changes

2022-02-12 12:04 UTC, ralphjsmit commented on packages/admin/config/filament.php
> +    'asset_path' => env('FILAMENT_PATH', '_filament'),
Done! Thanks👍

2022-02-12 15:02 UTC, ryangjchandler commented
@ralphjsmit I think we can leave the docs for now. Not sure if we've got any tests that make sure the asset paths return the correct response, etc. If not, would you be able to add some?

2022-02-14 13:36 UTC, ralphjsmit commented
@ryangjchandler No worries😊 I added a test for loading the asset files. Indeed better to have tests!

Btw, I saw that Filament currently does `uses(TestCase::class)` in every test file. Is there a particular reason for that or could we just switch to `uses(TestCase::class)->in(__DIR__)` in Pest? If needed, we can override the testcase in a specific file.

2022-02-17 22:18 UTC, merged

2022-02-17 22:18 UTC, danharrin commented
Thank you!