Dispatch an event when toggling dark mode
filamentphp/filament pull request #1585
Opened 2022-02-12 20:15 UTC by mohamedsabil83

2022-02-12 23:11 UTC, ryangjchandler requested changes

2022-02-12 23:11 UTC, ryangjchandler commented on packages/admin/resources/views/components/layouts/app/topbar/user-menu.blade.php
> +                    $dispatch('dark-mode-changed', { mode: 'dark' })
I prefer `dark-mode-toggled` personally.

2022-02-12 23:23 UTC, mohamedsabil83 commented on packages/admin/resources/views/components/layouts/app/topbar/user-menu.blade.php
> +                    $dispatch('dark-mode-changed', { mode: 'dark' })
Good advice 👌🏽

2022-02-12 23:35 UTC, ryangjchandler requested changes
I think we just need to fix some grammar in the docs and it'll be good to merge. Can imagine this will be handy for people who are building custom components etc. 

Will take a look at the docs tomorrow/Monday.

2022-02-13 09:07 UTC, danharrin commented
Thanks! I've removed the event payload object and just replaced it with a `dark` or `light` string.

2022-02-13 09:07 UTC, merged

2022-02-13 09:12 UTC, mohamedsabil83 commented
You're welcome. Yes, that's better 👍🏽