feature: add prefix/postfix support to select fields
filamentphp/filament pull request #1611
Opened 2022-02-14 16:00 UTC by jacksleight

This PR adds prefix/postfix support to select fields.

My use case for this is adding links to related records when using a BelongsToSelect, eg:

![Screenshot 2022-02-14 at 15 42 02](https://user-images.githubusercontent.com/126740/153897857-8145c8d2-cd8c-4fc7-a719-9211ad6cf631.png)

Notes:

* prefix/postfix properties and methods have been moved to a new `HasAffixes` trait
* `getPrefixLabel` and `getPostfixLabel` can now return more than just a string, so that an `HtmlString` object may be used
* As the `<select>` is no longer the root element the `filament-forms-select-component` class has been moved up to the new wrapper div. This is potentially a breaking change, but it does keep it consistent with other fields such as text-input.
    * Also the searchable version didn't include `filament-forms-select-component` at all, which this fixes
* I have added a `suffix` alias for `postfix`, as I think that's a bit more intuitive name, but no worries if you want that removed

2022-02-14 16:16 UTC, jacksleight commented
> @danharrin I wonder if linking from a `BelongsToSelect` is something we should support anyway?

It's quite useful, essentially the reverse of a Relation Manager (when set up to link directly to record pages), lets you jump back and fourth very easily.

2022-02-14 16:18 UTC, ryangjchandler commented
@jacksleight Yeah, I could do with this myself on an app tbh. The best way I think would be a `url()` method on the `BelongsToSelect` field that shows an icon or button.

2022-02-14 16:45 UTC, jacksleight commented
I could try adding that to this PR if you like?

2022-02-14 16:47 UTC, ryangjchandler commented
@jacksleight Feel free to give it a go - I'd definitely see it as a worthy addition.

2022-02-14 17:02 UTC, jacksleight commented
Example of how it all looks:

![Screenshot 2022-02-14 at 17 02 38](https://user-images.githubusercontent.com/126740/153911067-b1b797a4-a2dc-4e03-a202-62a981ab1b9b.png)

2022-02-14 17:09 UTC, ryangjchandler requested changes

2022-02-14 17:09 UTC, ryangjchandler commented on packages/forms/src/Components/Select.php
> +    protected string | Closure | null $url = null;
The Tables package has a `CanOpenUrl` trait, might be worth making a similar one for the forms package.

2022-02-14 20:56 UTC, jacksleight commented
Another feature that would be really handy (but probably way beyond the scope of this PR) would be the ability to create a new related record via a `BelongsToSelect`, just like the relation manager.

2022-02-15 14:35 UTC, saade commented
> Another feature that would be really handy (but probably way beyond the scope of this PR) would be the ability to create a new related record via a `BelongsToSelect`, just like the relation manager.

Yeah! that would be awesome, i asked about this a time ago [Here](https://discord.com/channels/883083792112300104/883085267383226478/936432730026172497) and Dan replied [Here](https://discord.com/channels/883083792112300104/883085267383226478/936524755048214588) i think that could be easy (maybe) with the new resource modals feature

2022-02-24 20:43 UTC, danharrin commented
Thanks for your work on this, but I'm going to remove the `url()` feature as I want to approach this differently in the future, so that we can support modal create / edit forms for select fields 👍

2022-02-24 20:49 UTC, merged