Add dusk selectors to form components
filamentphp/filament pull request #1794
Opened 2022-03-05 13:33 UTC by ralphjsmit

This adds `dusk="{{ $getStatePath() }}"` selectors to most form components, so that developers can more easily use the components in Dusk tests.

Below are a few examples:

```php
$browser
    // TextInputs & TextArea..
    ->type('@data.code', 'CODE')
    ->type('@data.description', 'Description.')
    ->type('@data.reuse_count', 2)
    // DatePicker...
    ->click('@data.start_at.open')
    ->screenshot('Opening picker')
    // January is month '0', so month '1' is February.
    ->select('@data.start_at.focusedMonth', '1')
    ->type('@data.start_at.focusedYear', '2023')
    ->click('@data.start_at.focusedDate.28')
    ->screenshot('After picking date')
    // Closing DatePicker by clicking somewhere..
    ->clickAtPoint(1, 1)
```

I must admit that I haven't been able to test every selector yet (though I tested most of them). That's why I didn't add anything to the docs about it yet. Most likely I'll be doing some more browser testing the coming weeks, so if I find a selector that needs an update, of course I'll PR that.

I choose for using the statepath, because the statepath maps directly to how the values of an input are stored in Livewire. Theoretically, if two components have the same statepath, their values in Livewire must always be the same. For the other part, developers should be smart enough to open up their browser inspector and figure out that everything starts with `data.` of whatever statepath they have.

2022-03-05 14:16 UTC, ryangjchandler commented
Are we also able to do this for the repeater and block editor fields? Would be good to have buttons & other parts of those components dusk-enabled.

2022-03-05 18:38 UTC, ralphjsmit commented
@ryangjchandler That would be possible indeed. The reason I skipped those was that I didn't have any repeater/block editor in the project I'm currently in, so I didn't have a good testcase. Those are the most complex components, and it didn't really feel like adding selectors out-of-the-blue would be a good idea. Next time I have a usecase for such a component I'll absolutely add them, but for now I didn't choose for it.

2022-03-06 11:06 UTC, danharrin commented
I think that the identifiers need prefixing with something to clarify that they are form components and not another UI element. Maybe `filament.forms.`? Open to other suggestions.

2022-03-06 12:47 UTC, ryangjchandler commented
Yeah, would go with `filament.` or `filament.forms`.

2022-03-07 06:37 UTC, ralphjsmit commented
Just to be sure, so the form will be `dusk=“filament.{{ $getStatePath() }}”`?

2022-03-07 07:52 UTC, danharrin commented
I think `filament.forms.` so that it doesn't get mixed up with possible table filters or columns.

2022-03-15 17:11 UTC, ralphjsmit commented
Updated the PR with the prefixes👍

2022-03-15 17:12 UTC, ryangjchandler requested changes

2022-03-15 17:15 UTC, ralphjsmit commented on packages/forms/resources/views/components/date-time-picker.blade.php
> +            x-ref="button"
Done!

2022-03-15 17:28 UTC, ryangjchandler approved these changes

2022-03-15 17:32 UTC, merged

2022-03-16 08:55 UTC, Wit3 commented
This PR create a bug in date-time-picker component, see the screenshot
![Immagine 2022-03-16 095417](https://user-images.githubusercontent.com/5450259/158552984-2209fa36-107b-4ee7-87e3-5d5f7337fdbe.png)

2022-03-16 09:26 UTC, ralphjsmit commented
@Wit3 Sorry for that! I opened a new PR with a fix (#1923).

2022-03-16 09:36 UTC, danharrin commented
Just released a new version with this fix