Feature: ActiveRelationManager keys
filamentphp/filament pull request #1964
Opened 2022-03-22 10:32 UTC by ZedoXmv

![image](https://user-images.githubusercontent.com/75579178/159462315-95c0836a-de54-4b61-887a-8da9bc80aa68.png)

Usage is similar to the syntax i suggested in https://github.com/laravel-filament/filament/discussions/1724#discussioncomment-2349148
> ```
> public static function getRelations(): array
> {
>     return [
>         'permissions' => RelationManagers\PermissionsRelationManager::class,
>         'users' => RelationManagers\UsersRelationManager::class,
>     ];
> }
> ```

If no keys are provided it will retain the old way, with the namespace
`activeRelationManager=App%5CFilament%5CResources%5CUserResource%5CRelationManagers%5CPostsRelationManager`

2022-03-22 11:03 UTC, ryangjchandler requested changes

2022-03-22 11:03 UTC, ryangjchandler commented on packages/admin/src/Resources/Pages/Concerns/HasRelationManagers.php
> +        };
semi-colon?
```suggestion
        }
```

2022-03-22 11:12 UTC, danharrin commented
I feel like we can simplify this and always use the keys of the array instead of checking `isAssoc`. Would result in relation managers without a key to have `activeRelationManager=1` in the query string, but this is arguably cleaner (but less clear) than using FQNs

2022-03-22 18:48 UTC, ZedoXmv commented
I tried without checking  for `isAssoc` at first, but couldn't get it working properly.
checkout to https://github.com/laravel-filament/filament/pull/1964/commits/f4d91af327a15971940797fed76c60e794bdf362
<img width="960" alt="image" src="https://user-images.githubusercontent.com/75579178/159553430-7293fbc2-8d27-4826-93be-d8080f815c1f.png">


not sure if im doing something wrong 🤷. any suggestions?

2022-03-22 19:01 UTC, ryangjchandler commented
`===` would probably be checking an `int === string`?

2022-03-23 04:37 UTC, ZedoXmv commented
I think the issue is due to non-unique id `id="{{ $activeManager }}" ` . 

https://github.com/laravel-filament/filament/blob/c9cd361474e3477ca8f20cabb2e89153e3005215/packages/admin/resources/views/components/resources/relation-managers/index.blade.php#L37-L46

2022-03-23 22:07 UTC, merged

2022-03-23 22:07 UTC, danharrin commented
Thanks