fix issue #1985 - FileUpload locale not work correctly
filamentphp/filament pull request #2027
Opened 2022-03-26 19:03 UTC by themahdavi

this change for fix issue #1985 .

my solution:
1- define array of available locale filename from filepond
2- search array for find site locale
3- set the currect name to url

2022-03-26 19:27 UTC, pxlrbt requested changes
Check the styling

2022-03-26 19:56 UTC, themahdavi commented
fix formatting on second commit (wip)

2022-03-26 20:17 UTC, pxlrbt requested changes

2022-03-26 20:17 UTC, pxlrbt commented on packages/forms/resources/views/components/file-upload.blade.php
> +                if(str_contains($availableLocale, $locale)){
```suggestion
            foreach ($allAvailableLocale as $availableLocale) {
                if (str_contains($availableLocale, $locale)) {
```

2022-03-26 20:20 UTC, pxlrbt commented
> fix formatting on second commit (wip)
> 
> meaning about styling ?

Sorry, somehow it didn't show the requested changes 🤷🏼‍♂️ Tried it again.

Also I think we don't need to try loading the locale, if it didn't match (Lines 18–20)
```html
<script type="module">
    import localeData from 'https://cdn.skypack.dev/filepond/locale/{{$locale}}.js'
    window.FilePond && window.FilePond.setOptions({ ...localeData, ...{!! $defaultLocaleData !!} })
</script>
        ```

2022-03-26 20:37 UTC, themahdavi commented
this pr just for load all available locale from filepond ... 
if not load and get error from get request haven't any idea
can use fallback_locale from laravel app.php config

2022-03-26 20:39 UTC, pxlrbt commented
> this pr just for load all available locale from filepond ...
> if not load and get error from get request haven't any idea
> can use fallback_locale from laravel app.php config

I don't think we need to check the request. Just whether the locale is in `allAvailableLocales`. If it's not there we don't need to import it.

2022-03-26 20:43 UTC, themahdavi commented
yep the default locale is EN and if the locale not contain in allAvailableLocale can ignore from send request.

commit now

2022-03-29 20:34 UTC, danharrin commented
Tbh, this is more of a Filepond issue than Filament. Only 3 Filepond locales use `_` instead of `-`. Surely, we should encourage that project to fix the inconsistency, instead of introducing this extra code to Filament?

2022-03-29 20:36 UTC, danharrin commented
Instead, maybe we should add a new translation key that allows you to define a Filepond locale string for that locale. Then we dont need that custom code, we can just read the locale from `__('forms::components.file_upload.filepond_locale')`

2022-03-30 07:39 UTC, pxlrbt commented
> Instead, maybe we should add a new translation key that allows you to define a Filepond locale string for that locale. Then we dont need that custom code, we can just read the locale from `__('forms::components.file_upload.filepond_locale')`

I guess that would be the best solution 😅

2022-04-07 15:57 UTC, merged