feature: introduce new `ReplicatorAction`
filamentphp/filament pull request #2128
Opened 2022-04-11 18:05 UTC by ryangjchandler

This pull request introduces a new first-party `ReplicatorAction`. I originally built this as a package for a project but figured it might be worth adding to core.

Here's the API:

```php
ReplicatorAction::make('replicate')
	// The `exclude()` method is used to tell the action which columns to be exclude when replicating.
	->exclude(['slug'])
	// `beforeSaving` can be used to provide a callback that will be invoked before saving the replica.
	->beforeSaving(function (Model $replica) {
		
	})
	// `afterSaving` can be used to provide a callback that will be invoked after saving the replica.
	->afterSaving(function (Model $replica) {

	});
```

By default, the action will appear as like a `LinkAction` but calling the `->button()` method will make it look like a button instead.

```php
ReplicatorAction::make('replicate')
	->button()
```

### Getting user input

Just like normal actions, you can provide a form schema that can be used to modify the replica before saving.

```php
ReplicatorAction::make('replicate')
	->exclude(['title'])
	->form([
		TextInput::make('title')
			->required(),
	])
	->beforeSaving(function (Model $replica, array $data) {
		$replica->fill($data);
	})
```

### Future scope

In the future, this could be expanded to support replicating relationships as well as the model.

2022-04-12 01:52 UTC, pxlrbt commented
Really useful. Thanks.

2022-04-19 12:32 UTC, danharrin requested changes

2022-04-19 12:32 UTC, danharrin commented on packages/tables/src/Actions/ReplicatorAction.php
> +    protected ?Closure $beforeSavingCallback = null;
```suggestion
    protected ?Closure $beforeReplicaSaved = null;
```

2022-04-19 12:32 UTC, danharrin commented on packages/tables/src/Actions/ReplicatorAction.php
> +    protected ?Closure $afterSavingCallback = null;
```suggestion
    protected ?Closure $afterReplicaSaved = null;
```

2022-04-19 12:32 UTC, danharrin commented on packages/tables/src/Actions/ReplicatorAction.php
> +    public function callBeforeSaving(Model $replica, array $data = []): void
```suggestion
    public function callBeforeReplicaSaved(Model $replica, array $data = []): void
```

2022-04-19 12:32 UTC, danharrin commented on packages/tables/src/Actions/ReplicatorAction.php
> +    public function callAfterSaving(Model $replica, array $data = []): mixed
```suggestion
    public function callAfterReplicaSaved(Model $replica, array $data = []): mixed
```

2022-04-19 12:32 UTC, danharrin commented on packages/tables/src/Actions/ReplicatorAction.php
> +    public function getView(): string
See first comment

2022-04-19 12:34 UTC, ryangjchandler commented on packages/tables/src/Actions/ReplicatorAction.php
> +    protected bool $isButton = false;
Yeah, we spoke about this. Will add.

2022-04-19 12:39 UTC, danharrin commented
Also, we'll need a short paragraph about this in the Actions docs I think

2022-04-19 15:47 UTC, danharrin commented
Any reason why the `type()` methods / property can't be on the base Action class (`Concerns\HasView`) instead?

2022-04-19 16:00 UTC, ryangjchandler commented
@danharrin That type method is gone now anyway. It wasn't needed since the methods are instead changing the `$view` directly.

2022-04-19 21:56 UTC, danharrin commented
Alright, just docs & translation strings to go then :) Lets set the default `label()` in `setUp()`.

2022-04-26 22:00 UTC, merged