Fix: RichEditor spacing when no buttons
filamentphp/filament pull request #2529
Opened 2022-05-24 12:21 UTC by johncarter-

When there are no buttons the toolbar `->disableAllToolbarButtons()` - the bar still shows, causing an extra line.
### Before

![image](https://user-images.githubusercontent.com/3776888/170033188-7ab35862-16fb-4972-b8a3-95625b3ff005.png)

#### After

![image](https://user-images.githubusercontent.com/3776888/170033418-4e412dd0-1d71-44fb-aa70-0c903047dd7d.png)

This conditionally hides the bar is no buttons.

Please let me know if you prefer a different syntax for the conditional class.

2022-05-24 13:25 UTC, ryangjchandler requested changes

2022-05-24 13:25 UTC, ryangjchandler commented on packages/forms/resources/views/components/rich-editor.blade.php
> +                    <div class="{{ count($getToolbarButtons()) > 0 ? 'flex' : 'hidden' }} justify-between space-x-4 rtl:space-x-reverse overflow-x-auto items-stretch overflow-y-hidden">
We should use the `@class` directive here for conditional classes.

2022-05-25 09:47 UTC, johncarter- commented
Removing the bar with the if directive results in a console error and the form failing to save:

![image](https://user-images.githubusercontent.com/3776888/170233188-cb13ecf9-b664-4d21-8872-ca9a8b445d1f.png)

I assumed it was a diffing issue so wrapped the if in a `div` but no joy. Shall I revert to CSS `hidden`?

2022-05-25 10:25 UTC, danharrin commented
Yeah thats fine, lets use `hidden` then. Trix must not like it

2022-05-26 19:29 UTC, danharrin commented
Btw, this entire issue is Chrome-only 😅 Safari wins for once

2022-05-26 19:47 UTC, danharrin commented
Also fixed #2514

Thanks John!

2022-05-26 19:47 UTC, merged

2022-05-27 06:17 UTC, johncarter- commented
Cheers Dan, sorry to leave you hanging there - I'm full-time Dadding at the mo.

2022-05-27 06:59 UTC, danharrin commented
No worries John! :)