Vite support
filamentphp/filament pull request #3100
Opened 2022-07-13 07:57 UTC by Z3d0X

Adds a 2nd argument to `registerTheme`

```diff
- public function registerTheme(string $url): void
+ public function registerTheme(string $url, bool $vite = false): void
```

### Example
```php
Filament::serving(function () {
    Filament::registerTheme(
        'resources/css/filament.css',
        vite: true,
    );
});
```

### TODO
- [ ] update docs

2022-07-13 08:08 UTC, ArtMin96 commented
maybe
```php
if ($vite) {
    $this->themeUsesVite = true;
}
```

to

```php
 $this->themeUsesVite = $vite;
```

2022-07-17 19:08 UTC, danharrin commented
Removed the extra param, now you can just do `Filament::registerTheme(app(Vite::class)('resources/css/filament.css')(`

2022-07-17 20:07 UTC, awcodes commented
This look good to me. Works as expected from a Filament standpoint.

One thing I would add is to put autoprefixer in the npm install command and the postcss.config.js file in the docs, since it is still recommended by tailwind in their postcss docs.

2022-07-17 20:14 UTC, zepfietje requested changes
Haven't tested locally, but code looks good to me.

As @awcodes mentioned, autoprefixer should be added to the postcss config in the docs ([this is also how Laravel Jetstream sets this up](https://github.com/laravel/jetstream/blob/2.x/stubs/livewire/postcss.config.js)).

2022-07-17 20:33 UTC, pxlrbt commented
Tested this with the demo and works.

2022-07-17 20:33 UTC, pxlrbt approved these changes

2022-07-17 20:56 UTC, merged

2022-07-17 20:56 UTC, danharrin commented
Added autoprefixer, thanks

2022-07-17 21:29 UTC, zepfietje commented on packages/admin/docs/07-appearance.md
> +And add Tailwind to the `postcss.config.js` file:
Should we add autoprefixer to this sentence as well, @danharrin?

2022-07-17 21:33 UTC, pxlrbt commented
@danharrin Seems like this causes issues with Laravel Mix. I didn't have that issue when testing with the default stylesheet, but when registering a theme `Filament::registerTheme(mix('css/filament.css'))`. 

Apparently `mix()` returns a HtmlString,

2022-07-17 21:37 UTC, danharrin commented
Oh... right. We can fix that.

2022-07-17 21:37 UTC, danharrin commented
hmmm

2022-07-17 21:38 UTC, danharrin commented
how do we differentiate between mix and vite now...

2022-07-17 21:41 UTC, danharrin commented
fixed

2022-07-17 21:42 UTC, danharrin commented
I hate it but its fine

<img width="635" alt="Screenshot 2022-07-17 at 22 42 08" src="https://user-images.githubusercontent.com/41773797/179425870-e015c3fe-e1cd-4fbf-9b3b-c226ec2a8be8.png">

2022-07-17 21:43 UTC, pxlrbt commented
Looks nasty, but I guess it works. Had the same idea about checking for `<script`