feature: add useful info to new `about` command
filamentphp/filament pull request #3176
Opened 2022-07-19 19:47 UTC by ryangjchandler

Should be backwards compatible with the `class_exists` check.

Replaces #2869.

2022-07-19 19:51 UTC, danharrin requested changes

2022-07-19 19:51 UTC, danharrin commented on packages/support/src/SupportServiceProvider.php
> +                'Views' => is_dir(resource_path('views/vendor/filament')) ? '<fg=red;options=bold>PUBLISHED</>' : '<fg=green;options=bold>NOT PUBLISHED</>',
I think we also need to check for `forms` and `tables` and `support`

2022-07-19 19:53 UTC, danharrin commented
Also you should bump the min Laravel version

2022-07-19 20:02 UTC, pxlrbt commented
> Also you should bump the min Laravel version
Don't think this is necessary:

> Should be backwards compatible with the class_exists check.

2022-07-19 20:10 UTC, danharrin commented
yeah but maybe we should still do that so more people have access to it

2022-07-19 20:12 UTC, pxlrbt commented
As we currently also support L8, I think we should keep it that way. If we were on L9 already, I guess it would be okay.

2022-07-19 20:17 UTC, danharrin commented
Thats not what I mean, we can bump the Laravel 9 *only* version so L8 users can still use it

2022-07-19 20:17 UTC, danharrin commented
It just forces current L9 users to upgrade Laravel at the same time as Filament

2022-07-19 20:18 UTC, ryangjchandler commented
I'd say leave as is.

2022-07-19 20:18 UTC, pxlrbt commented
I guess that would be fine.

2022-07-19 20:36 UTC, zepfietje commented
It would be possible that a user has different versions installed for the forms/tables packages if installed separately from `filament/filament`, right?

Not sure how often that happens, but it might be useful to show the versions per package. What do you think?

2022-07-19 20:42 UTC, danharrin commented
No, we use self.version so all packages have the same version

2022-07-19 20:50 UTC, zepfietje commented
> No, we use self.version so all packages have the same version

Even if you manually install just the forms and tables package? What about when pinning those to a specific version?

2022-07-19 20:56 UTC, danharrin commented
As far as I know there isnt a way around it

2022-07-24 08:13 UTC, danharrin requested changes

2022-07-24 08:13 UTC, danharrin commented on packages/support/src/SupportServiceProvider.php
> +                'Views' => is_dir(resource_path('views/vendor/filament')) ? '<fg=red;options=bold>PUBLISHED</>' : '<fg=green;options=bold>NOT PUBLISHED</>',
@ryangjchandler could you take a look at this when you have time please?

2022-07-24 12:21 UTC, merged

2022-07-24 12:21 UTC, danharrin commented
Fixed it all, thanks @ryangjchandler