Feature/per page all option
filamentphp/filament pull request #3666
Opened 2022-08-25 08:25 UTC by aymanalareqi

2022-08-25 21:59 UTC, zepfietje requested changes

2022-08-25 21:59 UTC, zepfietje commented on packages/tables/resources/views/components/pagination/records-per-page-selector.blade.php
> +        @if ($option === -1)
Could you fix the indentation here?

2022-08-25 21:59 UTC, zepfietje commented on packages/tables/src/Concerns/HasRecords.php
> +            (! $this->isTablePaginationEnabled()) || //($this->getTableRecordsPerPage() == -1) ||
Why is this commented out?

2022-08-25 22:14 UTC, aymanalareqi commented on packages/tables/src/Concerns/HasRecords.php
> +            (! $this->isTablePaginationEnabled()) || //($this->getTableRecordsPerPage() == -1) ||
I forget to delete it 😅

2022-08-25 22:43 UTC, aymanalareqi commented on packages/tables/resources/views/components/pagination/records-per-page-selector.blade.php
> +        @if ($option === -1)
I have fix it

2022-08-26 10:34 UTC, zepfietje requested changes

2022-08-26 10:34 UTC, zepfietje commented on packages/tables/resources/lang/en/table.php
> +        'all' => 'All',
Wouldn't it be better to move this translation key to `pagination.fields.records_per_page.options.all`?

2022-08-26 10:34 UTC, zepfietje commented on packages/tables/src/Concerns/CanPaginateRecords.php
> +    protected function isTablePaginationPerPageAllOptionEnabled(): bool
What's the reason behind having this method instead of just returning the option in the array from `getTableRecordsPerPageSelectOptions`?

2022-08-26 10:34 UTC, zepfietje commented on packages/tables/src/Concerns/CanPaginateRecords.php
> +        if ($perPage === -1) {
What about using `null` instead of `-1` as "all"?

2022-08-26 10:34 UTC, zepfietje commented on packages/tables/resources/views/components/pagination/records-per-page-selector.blade.php
> +                <option value="{{ $option }}">{{ $option }}</option>
We can remove this condition and just echo out `{{ $option ?? __('tables::table.pagination.all') }}` if we use `null` for "all".

2022-08-26 10:34 UTC, zepfietje commented on packages/tables/src/Concerns/CanPaginateRecords.php
> +        $option = config('tables.pagination.records_per_page_select_options', [5, 10, 25, 50]);
These changes can be reverted if following my suggestions.

2022-08-26 10:34 UTC, zepfietje commented on packages/tables/src/Concerns/CanPaginateRecords.php
> +            $perPage,
```suggestion
            $this->getTableRecordsPerPage() ?? $query->getCountForPagination(),
```

2022-08-26 12:15 UTC, zepfietje approved these changes

2022-08-26 13:57 UTC, aymanalareqi commented
Thank @zepfietje

2022-08-26 18:08 UTC, merged