feat: check missing translations command
filamentphp/filament pull request #3881
Opened 2022-09-05 22:00 UTC by saade

This PR introduces a new command to check if some lang is missing translation keys.

### Command Signature
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/14329460/188515392-1b46c37f-fbbd-4fd5-a4f8-350178699df8.png">

### Example usage (scanning published filament translations)
`php artisan filament:check-translations pt_BR`

### Example usage (scanning filament translations from vendor folder)
`php artisan filament:check-translations pt_BR --dir=vendor`

### Example usage (comparing against other base language)
`php artisan filament:check-translations pt_BR --baseLang=es`

### Command output example
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/14329460/188515596-0f695e53-c792-4a70-9b5a-f8dcee802737.png">

#### Note to maintainers:
This PR does not work for scanning the package translations without the Laravel core embracing it. But it should help developers to spot missing and deprecated translations inside their laravel app.

2022-09-06 09:00 UTC, pxlrbt commented
Can we reduce the output to one line per package?
How does the script recognize "outdated" translations?

2022-09-06 10:16 UTC, danharrin commented on packages/support/src/Commands/CheckMissingTranslationsCommand.php
> +                        $this->banner('success', 'Lang %s has no misssing or deprecated translation keys!', $lang);
```suggestion
                        $this->banner('success', 'Lang %s has no missing or deprecated translation keys!', $lang);
```

2022-09-06 10:16 UTC, danharrin commented on packages/support/src/Commands/CheckMissingTranslationsCommand.php
> +                        $this->banner('warning', 'Lang %s has %d misssing translation keys and %d deprecated translation keys.', $lang, $missingCount, $deprecatedCount);
```suggestion
                        $this->banner('warning', 'Lang %s has %d missing translation keys and %d deprecated translation keys.', $lang, $missingCount, $deprecatedCount);
```

2022-09-06 15:28 UTC, saade commented
@pxlrbt 
> Can we reduce the output to one line per package?

yes

> How does the script recognize "outdated" translations?

wdym by "outdated"? Translations that got updated, for example `Save` > `Save Record`, or translations thats not being used anymore? (i've called deprecated translations in that case)

2022-09-07 06:47 UTC, pxlrbt commented
> wdym by "outdated"? 

Yeah, I meant "deprecated". Sorry. Maybe we can rename that to "removed" to make it clearer? I thought that tells me which keys were updated since last time.

2022-09-16 10:38 UTC, zepfietje requested changes

2022-09-16 10:38 UTC, zepfietje commented on packages/support/src/Commands/CheckMissingTranslationsCommand.php
> +
The notifications package is missing from this list. There's translations for notifications as well since database notifications got introduced.

2022-09-16 19:51 UTC, saade commented
Hey! Sorry for the delay, did some refactoring and styling on this.

I think it came out cleanly than my first implementation.

I think its ready for review.

2022-09-17 11:09 UTC, danharrin commented
I've changed the formatting as it overflowed a lot when there were lots of keys on 1 line

<img width="1179" alt="Screenshot 2022-09-17 at 14 08 42" src="https://user-images.githubusercontent.com/41773797/190853672-06ede2d4-9ae2-4116-8c3b-a8d3c8022221.png">

2022-09-17 11:10 UTC, danharrin commented
Also I've swapped the `dir` argument for `source`, and the default is `vendor` to encourage people to PR their translations.

2022-09-17 11:22 UTC, merged

2022-09-17 12:53 UTC, zepfietje commented
Great work, guys! Really like how this turned out. 🔥

2022-09-17 17:40 UTC, saade commented
Thanks Dan! Looks good!